### ISSUE TITLE
Video preview image becomes invisible when text is long

### ISSUE THREAD

**Issue by dlemmermann** [dlemmermann/jfxcentral2#423]
It seems like the text "wins" and pushes the image out of the box.

<img width="1386" alt="Bildschirmfoto 2023-08-16 um 13 08 09" src="https://github.com/dlemmermann/jfxcentral2/assets/9534301/afe0ea4d-4fdb-4e94-93e6-d307af69be98">

**Comment by leewyatt** [comment]
![image](https://github.com/dlemmermann/jfxcentral2/assets/75261429/ed281fe7-8400-40f3-9ed1-05b1eb056233)
![image](https://github.com/dlemmermann/jfxcentral2/assets/75261429/85673bbd-8212-42fe-90b6-13c577601d58)
The reason has been identified. It's because the current permissions for these videos are set to 'private', making them inaccessible from the outside. That's why we can't retrieve valid thumbnails.
